export const GET_PRODUCTS_DATA_REQUEST = 'GET_PRODUCTS_DATA_REQUEST'
export const GET_PRODUCTS_DATA_SUCCESS = 'GET_PRODUCTS_DATA_SUCCESS'
export const GET_PRODUCTS_DATA_ERROR = 'GET_PRODUCTS_DATA_ERROR'

export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR'
